CREATE TABLE KAN_GRUBU(
    KAN_GRUBU_ID INT  PRIMARY KEY,
    KANGRUBU  VARCHAR(10)
);

CREATE TABLE CINSIYET(
    CINSIYET_ID VARCHAR(5) PRIMARY KEY,
    CINSIYET VARCHAR(10)
);

CREATE TABLE HASTANE(
    HASTANE_ID INT PRIMARY KEY,
    HASTANE_ADI VARCHAR(50),
    HASTANE_ADRESI VARCHAR(100)
);

--KAN_BANKASI Tablosunun oluşturulması
CREATE TABLE KAN_BANKASI(
    KAN_BANKASI_ID INT PRIMARY KEY,
    KAN_BANKASI_ADI VARCHAR(50),
    KAN_BANKASI_ADRESI VARCHAR(50)
);

-- HASTALAR Tablosunun oluşturulması
CREATE TABLE HASTALAR (
    HASTA_ID INT PRIMARY  KEY,
    HASTA_ADI VARCHAR(50),
    HASTA_SOYADI VARCHAR(50),
    DOGUM_TARIHI DATE,
    CINSIYET_ID VARCHAR(5),
    KAN_GRUBU_ID INT,
    HASTANE_ID INT,
    FOREIGN KEY (CINSIYET_ID) REFERENCES CINSIYET(CINSIYET_ID),
    FOREIGN KEY (KAN_GRUBU_ID) REFERENCES KAN_GRUBU(KAN_GRUBU_ID),
    FOREIGN KEY (HASTANE_ID) REFERENCES HASTANE(HASTANE_ID)
);
---- BAGISCILAR TABLOSU OLUŞTURULMASI

CREATE TABLE BAGISCILAR(
    BAGISCI_ID INT PRIMARY KEY,
    BAGISCI_ADI VARCHAR(50),
    BAGISCI_SOYADI VARCHAR(50),
    BAGISCI_ADRESI VARCHAR(50),
    B_ILETISIM_NUM VARCHAR(15),
    KAN_GRUBU_ID INT,
    CINSIYET_ID VARCHAR(5),
    KAN_BANKASI_ID INT,
    FOREIGN KEY (CINSIYET_ID) REFERENCES CINSIYET(CINSIYET_ID),
    FOREIGN KEY (KAN_GRUBU_ID) REFERENCES KAN_GRUBU(KAN_GRUBU_ID),
    FOREIGN KEY (KAN_BANKASI_ID) REFERENCES KAN_BANKASI(KAN_BANKASI_ID)
);
