 --Bağışçı eklendiğinde stokta stok miktarını arttırma trigger'ı
CREATE OR REPLACE TRIGGER STOK_ARTTIR_TRIG
AFTER INSERT ON BAGISCILAR
FOR EACH ROW
BEGIN
  UPDATE STOK
  SET STOK_MIKTARI = STOK_MIKTARI + 1
  WHERE KAN_GRUBU_ID = :NEW.KAN_GRUBU_ID;
END;

--Hasta eklendiğinde stokta stok miktarını azaltma trigger'ı
CREATE OR REPLACE TRIGGER STOK_AZALT_TRIG
AFTER INSERT ON HASTALAR
FOR EACH ROW
BEGIN
  UPDATE STOK
  SET STOK_MIKTARI = STOK_MIKTARI - 1
  WHERE KAN_GRUBU_ID = :NEW.KAN_GRUBU_ID;
END;
